Fix Reproducibility https://github.com/chansey97/DeepQLearning/issues/1
On 2025/07/24, tried [Windows Wednesday - Windows Subsystem for Linux on Windows 11](https://www.youtube.com/watch?v=pNwatyeXplY) with the following issues:

1. `22.55 E: Unable to locate package python-opengl`, when docker build,

   Reason: Only `python3-opengl` exists in tensorflow/tensorflow:latest-gpu

   Workaround: Use older version of `tensorflow/tensorflow` docker image.

2. `Exception has occurred: DependencyNotInstalled` when press "Run and Debug"

   Reason: `pygame is not installed`

   Workaround: Add `pygame` to requirements.txt

3. `Model loading failure` when start debug

   To see details, add debug code to https://github.com/chansey97/DeepQLearning/blob/f694094459731bfe84991e7b51dc59379cca2170/lunarLanding.py#L96

   ```
   except Exception as e:
       print("Model loading failure", str(e))
   ```
   , which prints

   > Model loading failure File format not supported: filepath=./good_run_save/300/weights. Keras 3 only supports V3 .keras and .weights.h5 files, or legacy V1/V2 .h5 files.

   Reason: Tensorflow 2.16.1 uses Keras 3 which doesn't support checkpoint format, see https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1

   Workaround: Use older version of `tensorflow/tensorflow` docker image.

4. `Exception has occurred: ValueError` when press "Run and Debug"
   ```
    Can't convert non-rectangular Python sequence to Tensor.
      File "/workspaces/DeepQLearning-master/lunarLanding.py", line 82, in _reshapeState
        return tf.reshape(state, [1, STATE_SPACE_SIZE])
      File "/workspaces/DeepQLearning-master/lunarLanding.py", line 85, in testPolicy
        output = self.model(self._reshapeState(state))
      File "/workspaces/DeepQLearning-master/lunarLanding.py", line 244, in test
        action = moonLander.testPolicy(state)
      File "/workspaces/DeepQLearning-master/lunarLanding.py", line 260, in <module>
        test()
    ValueError: Can't convert non-rectangular Python sequence to Tensor.
   ```

   Reason: gym 0.26.0 introduced a break changes for the return values of `env.rest` and `env.step`, see https://github.com/openai/gym/releases/tag/0.26.0

   Workaround: Set `gym[atari]==0.25.2` in requirements.txt.

5. `Exception has occurred: TypeError` when press "Run and Debug"

   ```
   Exception has occurred: TypeError
   __init__() missing 2 required positional arguments: 'loadPath' and 'loadEpisode'
   File "/workspaces/DeepQLearning-master/lunarLanding.py", line 207, in train
    moonLander = LanderBrain()
   File "/workspaces/DeepQLearning-master/lunarLanding.py", line 272, in <module>
     train()
   TypeError: __init__() missing 2 required positional arguments: 'loadPath' and 'loadEpisode'
   ```

   Reason: : class LanderBrain defines two __init__ methods

   Workaround: achieve similar functionality by providing default values for some of the parameters, see https://stackoverflow.com/a/77001320/4518482

I chose `tensorflow/tensorflow:2.7.4-gpu` because gym 0.26.0 (released Sep 7, 2022) and TensorFlow 2.7.4 (released Sep 3, 2022) are most likely compatible.

Ultimately, when clicking "Debug and Run" in VS Code 1.102.2 (newest version 2025/07/24), a error dialog appears "The minimum supported Python version for the debugger extension is 3.9" (current is 3.8.10) - but testing confirms it doesn't affect actual debugging functionality and can be ignored.